
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservice?requireSSL=true&useSSL=true&verifyServerCertificate=false&serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: microservice-movie-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka, http//localhost:8762/eureka
  instance:
    prefer-ip-address: true

server:
  port: 8010



